### ISSUE TITLE
ACL() filedef should accept path defined as bytes 

### ISSUE THREAD

**Issue by ikus060** [iustin/pylibacl#16]
Current implementation accept `ACL(file=b'path_as_bytes')` but it doesn't support ACL(filedef='/path_as_bytes')`.

Looking at the code implementation is a simple mather of passing the right "format" with "et" instead of "s" for the filedef parameter.

**Comment by iustin** [comment]
Support for bytes and path objects was introduced in 707c0d4a, a while back, but I didn't make a release in a long while. Version 0.6.0 which I released a couple of weeks back has it, and it's already Debian testing (and will be in next stable) and in Ubuntu Hirsute Hippo. Sorry for delaying the release that much!
