### ISSUE TITLE
Cannot handle "default" tags

### ISSUE THREAD

**Issue by cweickhmann** [iustin/pylibacl#19]
Pylibacl does not seem to handle `default` entries of ACLs which are important e.g. for Samba4 permission management.

**Example:**
```bash
$ getfacl Folder1

# file: LC
# owner: 3000043
# group: 3000062
user::rwx
user:3000512:rwx
group::r-x
group:3000512:rwx
mask::rwx
other::---
default:user::rwx
default:user:3000512:rwx
default:group::r-x
default:group:3000512:rwx
default:other::---
```

Output of `print(acl)` of that folder:
```bash
user::rwx
user:3000512:rwx
group::r-x
group:3000512:rwx
mask::rwx
other::---
```

Notice the `default` entries are all gone.

Applies to versions 0.5.4 and 0.6.0 as far as I can tell.

**Comment by iustin** [comment]
As many times, getfacl is a too high level interface and creates wrong expectations.

At directory level, there are actual two ACLs involved: the ACL for the directory, and the default ACL. They're two separate ACL, there's not "default" key in the directory ACL itself.

See here: https://pylibacl.k1024.org/module.html#posix1e.ACL for the right way to read the default ACL from a directory.

**Comment by cweickhmann** [comment]
Dear @iustin,

thanks for the reply! Indeed, my issue was incorrect. Due to my own stupidity, the normal and the default values on the file I tested were identical in the first place.
For anyone else running into the same trap, here's how it should be done:

```bash
$ mkdir TestDir
$ getfacl TestDir/
# file: TestDir/
# owner: user1
# group: user1
user::rwx
group::r-x
other::r-x
```

Now, adding ACLs:

```bash
$ setfacl -m u:user2:rx TestDir/
$ setfacl -m g:group1:rx TestDir/
$ setfacl -m d:u:user3:rwx TestDir/
$ setfacl -m d:g:group2:rwx TestDir/
```

And in Python, using posix1e:

```python
>>> import posix1e as p
>>> acl = p.ACL(file="TestDir")
>>> default_acl = p.ACL(filedef="TestDir")
>>> print(acl)
user::rwx
user:user2:r-x
group::r-x
group:group1:r-x
mask::r-x
other::r-x

>>> print(default_acl)
user::rwx
user:user3:rwx
group::r-x
group:group2:rwx
mask::rwx
other::r-x
```

So, it *is* in fact working as expected. Sorry for the inconvenience.

**Comment by iustin** [comment]
No inconvenience at all, glad you made it work!
