### ISSUE TITLE
pip install warning about not being able to find .egg-info directory with python 2.7

### ISSUE THREAD

**Issue by yaneurabeya** [iustin/pylibacl#4]
It seems that pip install gets confused when installing the sources from git (look for the .egg-info directory warning):

<pre>
$ python -V
Python 2.7.8
$ pip --version
pip 1.5.6 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ sudo pip install --verbose -U .
Unpacking /home/ngie/onefs/branches/BR_RIPT_ATF2_MAKEQA2/test/src/pylibacl.new
  Running setup.py (path:/tmp/pip-EkO9KD-build/setup.py) egg_info for package from file:///home/ngie/onefs/branches/BR_RIPT_ATF2_MAKEQA2/test/src/pylibacl.new
    running egg_info
    creating pip-egg-info/pylibacl.egg-info
    writing pip-egg-info/pylibacl.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pylibacl.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pylibacl.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pylibacl.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/pylibacl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/pylibacl.egg-info/SOURCES.txt'
Installing collected packages: pylibacl
  Found existing installation: pylibacl 0.5.2
    Uninstalling pylibacl:
      Removing file or directory /usr/local/lib/python2.7/site-packages/pylibacl-0.5.2-py2.7.egg-info
      Successfully uninstalled pylibacl
  Running setup.py install for pylibacl
    running install
    running build
    running build_ext
    building 'posix1e' extension
    creating build
    creating build/temp.freebsd-11.0-CURRENT-amd64-2.7
    cc -fno-strict-aliasing -O2 -pipe -fno-strict-aliasing -DNDEBUG -fPIC -DHAVE_FREEBSD -DHAVE_LEVEL2 -I/usr/local/include/python2.7 -c acl.c -o build/temp.freebsd-11.0-CURRENT-amd64-2.7/acl.o
    creating build/lib.freebsd-11.0-CURRENT-amd64-2.7
    cc -shared -pthread build/temp.freebsd-11.0-CURRENT-amd64-2.7/acl.o -o build/lib.freebsd-11.0-CURRENT-amd64-2.7/posix1e.so
    running install_lib
    copying build/lib.freebsd-11.0-CURRENT-amd64-2.7/posix1e.so -> /usr/local/lib/python2.7/site-packages
    running install_egg_info
    running egg_info
    creating pylibacl.egg-info
    writing pylibacl.egg-info/PKG-INFO
    writing top-level names to pylibacl.egg-info/top_level.txt
    writing dependency_links to pylibacl.egg-info/dependency_links.txt
    writing manifest file 'pylibacl.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pylibacl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pylibacl.egg-info/SOURCES.txt'
    Copying pylibacl.egg-info to /usr/local/lib/python2.7/site-packages/pylibacl-0.5.2-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-gM1PcS-record/install-record.txt'
  Could not find .egg-info directory in install record for pylibacl==0.5.2 from file:///home/ngie/onefs/branches/BR_RIPT_ATF2_MAKEQA2/test/src/pylibacl.new in /usr/local/lib/python2.7/site-packages
Successfully installed pylibacl
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
</pre>

**Comment by iustin** [comment]
Unfortunately, I can't reproduce this on Debian with the same pip version and Python 2.7.9. The log is very similar, except for the missing "Could not find .egg-info" message.

What do you have in `/usr/local/lib/python2.7/site-packages` after pip install runs?

**Comment by iustin** [comment]
On FreeBSD11-current, with a fresh checkout from 0.5.2 git:

```
  Running setup.py install for pylibacl
    Running command /usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-XCJlwl-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FxjddT-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_ext
    building 'posix1e' extension
    creating build
    creating build/temp.freebsd-11.0-CURRENT-amd64-2.7
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -DHAVE_FREEBSD -I/usr/local/include/python2.7 -c acl.c -o build/temp.freebsd-11.0-CURRENT-amd64-2.7/acl.o
    creating build/lib.freebsd-11.0-CURRENT-amd64-2.7
    cc -shared -lpthread -Wl,-rpath,/usr/lib:/usr/local/lib -Wl,-rpath=/usr/lib:/usr/local/lib -L/usr/local/lib -fstack-protector build/temp.freebsd-11.0-CURRENT-amd64-2.7/acl.o -L/usr/local/lib -lpython2.7 -o build/lib.freebsd-11.0-CURRENT-amd64-2.7/posix1e.so
    running install_lib
    copying build/lib.freebsd-11.0-CURRENT-amd64-2.7/posix1e.so -> /usr/local/lib/python2.7/site-packages
    running install_egg_info
    running egg_info
    creating pylibacl.egg-info
    writing pylibacl.egg-info/PKG-INFO
    writing top-level names to pylibacl.egg-info/top_level.txt
    writing dependency_links to pylibacl.egg-info/dependency_links.txt
    writing manifest file 'pylibacl.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pylibacl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pylibacl.egg-info/SOURCES.txt'
    Copying pylibacl.egg-info to /usr/local/lib/python2.7/site-packages/pylibacl-0.5.2-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-FxjddT-record/install-record.txt'
Successfully installed pylibacl-0.5.2
Cleaning up...
```

So no .egg-info issues. I think it was either a transiet issue with the python/easysetup packages, or something local to your installation.

I'm going to mark as unreproducible, feel free to reopen if you hit this again.
