### ISSUE TITLE
ModificationTests fails on FreeBSD 11 with EINVAL

### ISSUE THREAD

**Issue by yaneurabeya** [iustin/pylibacl#5]
This was on UFS with POSIX1e ACL support enabled:

<pre>
======================================================================
ERROR: testStr (__main__.ModificationTests)
Test str() of an ACL.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/acls/test_acls.py", line 218, in testStr
    str_acl = str(acl)
IOError: [Errno 22] Invalid argument
</pre>

**Comment by iustin** [comment]
> The default if there aren't any entries should probably be to print out an empty string, correct?

Empty ACLs are not "valid" (see `testFromEmpty`), but it seems that Linux is happy to convert an invalid ACL to string, whereas other OSes might not be. I'll switch to proper ACLs in the tests where needed.
