### ISSUE TITLE
testMultipleBadEntries doesn't check for errno == EINVAL

### ISSUE THREAD

**Issue by yaneurabeya** [iustin/pylibacl#6]
According to acl_calc_mask on FreeBSD, the function should fail with EINVAL if one or more of the ACLs passed in is invalid. Not sure if this is the cause of the failure though, but it seems likely...

<pre>
======================================================================
ERROR: testMultipleBadEntries (__main__.ModificationTests)
Test multiple invalid entries
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/acls/test_acls.py", line 292, in testMultipleBadEntries
    acl.calc_mask()
IOError: [Errno 22] Invalid argument
</pre>

<pre>
     The acl_calc_mask() function fails if:

     [EINVAL]           Argument acl_p does not point to a pointer to a valid
                        ACL.
</pre>

**Comment by iustin** [comment]
Thanks for the info, will fix.
