### ISSUE TITLE
testAppend and testDelete fail on FreeBSD 11

### ISSUE THREAD

**Issue by yaneurabeya** [iustin/pylibacl#7]
If I enable LEVEL2, the testAppend and testDelete testcases fail on FreeBSD 11:

<pre>
$ sudo tunefs -p /build/acls/ 2>&1 | grep POSIX
tunefs: POSIX.1e ACLs: (-a)                                enabled
$ uname -a
FreeBSD ngie-fbsd-current 11.0-CURRENT FreeBSD 11.0-CURRENT #0 2b0a902(isilon-atf): Fri Aug  1 05:37:08 PDT 2014     root@ngie-fbsd-current:/usr/obj/usr/src/sys/GENERIC  amd64
$ (cd /build/acls/; sudo python /build/acls/test_acls.py )
.........EE.E.....E..
======================================================================
ERROR: testAppend (__main__.ModificationTests)
Test append a new Entry to the ACL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/acls/test_acls.py", line 227, in testAppend
    acl.calc_mask()
IOError: [Errno 22] Invalid argument

======================================================================
ERROR: testDelete (__main__.ModificationTests)
Test delete Entry from the ACL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/acls/test_acls.py", line 237, in testDelete
    acl.calc_mask()
IOError: [Errno 22] Invalid argument
</pre>

**Comment by iustin** [comment]
This is most likely the same issue as #6 - here the ACL is invalid with just one entry, so calc_mask will fail.

I'll need to spin up a FreeBSD VM to properly test this.

**Comment by iustin** [comment]
OK, didn't get the proper commit message syntax, but this should be fixed as well.
